version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - "DB_SERVER_ADDRESS=database.ngxuanhoang.id.vn"
      - "DB_SERVER_PORT=3306"
      - "DB_USER=hca_test"
      - "DB_PASSWORD=Hca@123"