version: '3.8'

services:
  app:
    image: 'nxhdev2002/hca-spring-app'
    container_name: app
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - "DB_SERVER_ADDRESS=10.8.0.254"
      - "DB_SERVER_PORT=3306"
      - "DB_USER=hca_dev"
      - "DB_PASSWORD=Hca@123"
    network_mode: bridge