spring:
  datasource:
    url: jdbc:mysql://${DB_SERVER_ADDRESS:10.8.0.1}:${DB_SERVER_PORT:3306}/hca_test
    username: ${DB_USER:hca_dev}
    password: ${DB_PASSWORD:Hca@123}

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true


springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: com.hca

management:
  endpoint:
    health:
      show-details: ALWAYS
    endpoints:
      web:
        exposure:
          include: "*"

logging:
  level:
    org.springframework: INFO
    com.hca: INFO

## FIXME : Customize JWT token and Swagger information for your application

jwt:
  secretKey: 8cZXigXYSl7HULXkJim3ml442EMznNXR
  issuer: hca
  expirationMinute: 30

swagger:
  contact-name: HCA
  contact-mail: hca@gmail.com
  contact-url: https://hca.com
  app-name: HCA PROJECT
  app-description: "HCA 2023"
  app-version: 1.0.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0

